name: Check & Release
on: [push, pull_request]
jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Format and check with shfmt
      uses: bltavares/actions/shfmt@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHFMT_ARGS: -i 2 -ci
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lint docker file (docker-lint)
      uses: docker://cdssnc/docker-lint-github-action
      with:
        args: --ignore DL3007 --ignore DL3018
  release:
    runs-on: ubuntu-latest
    needs: [shfmt, lint]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Create GitHub release
      uses: Roang-zero1/github-create-release-action@master
      with:
        version_regex: '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'
        update_existing: 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
